In [15]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ASUS\Desktop\Desktop\Infotact Internship\Healthcare & Medical - Chronic Disease  Prediction and EHR Analysis\dataset\heart_disease_uci.csv")

print("First 5 rows of the dataset:")
display(df.head())

First 5 rows of the dataset:

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [16]:
print("Dataset information:")
display(df.info())

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    str
 3   dataset   920 non-null    str
 4   cp        920 non-null    str
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    str
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    str
 13  ca        309 non-null    float64
 14  thal      434 non-null    str
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(2), str(6)
memory usage: 156.4+ KB

None

In [17]:
print("Descriptive statistics of the dataset:")
display(df.describe())

Descriptive statistics of the dataset:

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [18]:
# Check unique values and their counts for 'object' type columns
object_cols = df.select_dtypes(include='object').columns
for col in object_cols:
    print(f"\nUnique values for column '{col}':")
    print(df[col].value_counts(dropna=False))

Unique values for column 'sex':
sex
Male      726
Female    194
Name: count, dtype: int64

Unique values for column 'dataset':
dataset
Cleveland        304
Hungary          293
VA Long Beach    200
Switzerland      123
Name: count, dtype: int64

Unique values for column 'cp':
cp
asymptomatic       496
non-anginal        204
atypical angina    174
typical angina      46
Name: count, dtype: int64

Unique values for column 'fbs':
fbs
False    692
True     138
NaN       90
Name: count, dtype: int64

Unique values for column 'restecg':
restecg
normal              551
lv hypertrophy      188
st-t abnormality    179
NaN                   2
Name: count, dtype: int64

Unique values for column 'exang':
exang
False    528
True     337
NaN       55
Name: count, dtype: int64

Unique values for column 'slope':
slope
flat           345
NaN            309
upsloping      203
downsloping     63
Name: count, dtype: int64

Unique values for column 'thal':
thal
NaN                  486
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1090739161.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include='object').columns

In [19]:
# Check values in 'trestbps' and 'chol' that are 0, which might indicate missing values.
print("\nValue counts for 'trestbps' where value is 0:")
print(df[df['trestbps'] == 0]['trestbps'].count())

print("\nValue counts for 'chol' where value is 0:")
print(df[df['chol'] == 0]['chol'].count())

Value counts for 'trestbps' where value is 0:
1

Value counts for 'chol' where value is 0:
172

In [20]:
# Replace '?' with NaN in relevant columns
df.replace('?', pd.NA, inplace=True)

# Replace 0 with NaN in 'trestbps' and 'chol' as these are not physiologically possible
df['trestbps'] = df['trestbps'].replace(0, pd.NA)
df['chol'] = df['chol'].replace(0, pd.NA)

# Convert 'num' to a binary target variable (0: no disease, 1: disease present)
df['num'] = df['num'].apply(lambda x: 1 if x > 0 else 0)
df.rename(columns={'num': 'heart_disease_present'}, inplace=True)

# Drop the 'id' column as it's not relevant for analysis
df.drop('id', axis=1, inplace=True)

# Display the updated info and head to see changes
display(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    920 non-null    int64
 1   sex                    920 non-null    str
 2   dataset                920 non-null    str
 3   cp                     920 non-null    str
 4   trestbps               860 non-null    object
 5   chol                   718 non-null    object
 6   fbs                    830 non-null    object
 7   restecg                918 non-null    str
 8   thalch                 865 non-null    float64
 9   exang                  865 non-null    object
 10  oldpeak                858 non-null    float64
 11  slope                  611 non-null    str
 12  ca                     309 non-null    float64
 13  thal                   434 non-null    str
 14  heart_disease_present  920 non-null    int64
dtypes: float64(3), int64(2), object(4), str(6)
memory usage: 149.2+ KB

None

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,heart_disease_present
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [21]:
# Display updated info to verify changes, especially NaN counts
display(df.info())

# Display the first few rows to see the new 'heart_disease_present' column and overall structure
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    920 non-null    int64
 1   sex                    920 non-null    str
 2   dataset                920 non-null    str
 3   cp                     920 non-null    str
 4   trestbps               860 non-null    object
 5   chol                   718 non-null    object
 6   fbs                    830 non-null    object
 7   restecg                918 non-null    str
 8   thalch                 865 non-null    float64
 9   exang                  865 non-null    object
 10  oldpeak                858 non-null    float64
 11  slope                  611 non-null    str
 12  ca                     309 non-null    float64
 13  thal                   434 non-null    str
 14  heart_disease_present  920 non-null    int64
dtypes: float64(3), int64(2), object(4), str(6)
memory usage: 149.2+ KB

None

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,heart_disease_present
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [22]:
# Convert 'trestbps' and 'chol' to numeric, coercing errors to NaN
df['trestbps'] = pd.to_numeric(df['trestbps'], errors='coerce')
df['chol'] = pd.to_numeric(df['chol'], errors='coerce')

# Convert 'fbs' and 'exang' to boolean type
df['fbs'] = df['fbs'].astype('boolean')
df['exang'] = df['exang'].astype('boolean')

# Display updated info to verify data type changes
display(df.info())

# Display the first few rows to see the effect of type conversion
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    920 non-null    int64
 1   sex                    920 non-null    str
 2   dataset                920 non-null    str
 3   cp                     920 non-null    str
 4   trestbps               860 non-null    float64
 5   chol                   718 non-null    float64
 6   fbs                    830 non-null    boolean
 7   restecg                918 non-null    str
 8   thalch                 865 non-null    float64
 9   exang                  865 non-null    boolean
 10  oldpeak                858 non-null    float64
 11  slope                  611 non-null    str
 12  ca                     309 non-null    float64
 13  thal                   434 non-null    str
 14  heart_disease_present  920 non-null    int64
dtypes: boolean(2), float64(5), int64(2), str(6)
memory usage: 138.5 KB

None

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,heart_disease_present
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [23]:
# Impute missing values for numerical columns with the median
for col in ['trestbps', 'chol', 'thalch', 'oldpeak', 'ca']:
    if df[col].isnull().any():
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)

# Impute missing values for categorical columns with the mode
for col in ['fbs', 'restecg', 'exang', 'slope', 'thal']:
    if df[col].isnull().any():
        mode_val = df[col].mode()[0] # .mode() can return multiple values, take the first one
        df[col].fillna(mode_val, inplace=True)

# Display updated info to verify no more missing values
display(df.info())

# Display the first few rows to see the effect of imputation
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    920 non-null    int64
 1   sex                    920 non-null    str
 2   dataset                920 non-null    str
 3   cp                     920 non-null    str
 4   trestbps               860 non-null    float64
 5   chol                   718 non-null    float64
 6   fbs                    830 non-null    boolean
 7   restecg                918 non-null    str
 8   thalch                 865 non-null    float64
 9   exang                  865 non-null    boolean
 10  oldpeak                858 non-null    float64
 11  slope                  611 non-null    str
 12  ca                     309 non-null    float64
 13  thal                   434 non-null    str
 14  heart_disease_present  920 non-null    int64
dtypes: boolean(2), float64(5), int64(2), str(6)
memory usage: 138.5 KB

C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1665798832.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(mode_val, inplace=True)

None

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,heart_disease_present
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [24]:
# One-hot encode categorical columns
categorical_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Display updated info and head to see changes after one-hot encoding
display(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  860 non-null    float64
 2   chol                      718 non-null    float64
 3   fbs                       830 non-null    boolean
 4   thalch                    865 non-null    float64
 5   exang                     865 non-null    boolean
 6   oldpeak                   858 non-null    float64
 7   ca                        309 non-null    float64
 8   heart_disease_present     920 non-null    int64
 9   sex_Male                  920 non-null    bool
 10  dataset_Hungary           920 non-null    bool
 11  dataset_Switzerland       920 non-null    bool
 12  dataset_VA Long Beach     920 non-null    bool
 13  cp_atypical angina        920 non-null    bool
 14  cp_non-anginal            920 non-null    bool
 15  cp_typical angina         920 non-null    bool
 16  restecg_normal            920 non-null    bool
 17  restecg_st-t abnormality  920 non-null    bool
 18  slope_flat                920 non-null    bool
 19  slope_upsloping           920 non-null    bool
 20  thal_normal               920 non-null    bool
 21  thal_reversable defect    920 non-null    bool
dtypes: bool(13), boolean(2), float64(5), int64(2)
memory usage: 65.7 KB

C:\Users\ASUS\AppData\Local\Temp\ipykernel_32896\1812772813.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

None

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,heart_disease_present,sex_Male,...,dataset_VA Long Beach,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,True,150.0,False,2.3,0.0,0,True,...,False,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3.0,1,True,...,False,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,False,129.0,True,2.6,2.0,1,True,...,False,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,False,187.0,False,3.5,0.0,0,True,...,False,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,False,172.0,False,1.4,0.0,0,False,...,False,True,False,False,False,False,False,True,True,False

In [27]:
# Export the cleaned DataFrame to a CSV file
df.to_csv('heart_disease_cleaned.csv', index=False)

print("Cleaned dataset exported successfully to 'heart_disease_cleaned.csv'")

Cleaned dataset exported successfully to 'heart_disease_cleaned.csv'

In [25]:
# One-hot encode categorical columns
categorical_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Display updated info and head to see changes after one-hot encoding
display(df.info())
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  860 non-null    float64
 2   chol                      718 non-null    float64
 3   fbs                       830 non-null    boolean
 4   thalch                    865 non-null    float64
 5   exang                     865 non-null    boolean
 6   oldpeak                   858 non-null    float64
 7   ca                        309 non-null    float64
 8   heart_disease_present     920 non-null    int64
 9   sex_Male                  920 non-null    bool
 10  dataset_Hungary           920 non-null    bool
 11  dataset_Switzerland       920 non-null    bool
 12  dataset_VA Long Beach     920 non-null    bool
 13  cp_atypical angina        920 non-null    bool
 14  cp_non-anginal            920 non-null    bool
 15  cp_typical angina         920 non-null    bool
 16  restecg_normal            920 non-null    bool
 17  restecg_st-t abnormality  920 non-null    bool
 18  slope_flat                920 non-null    bool
 19  slope_upsloping           920 non-null    bool
 20  thal_normal               920 non-null    bool
 21  thal_reversable defect    920 non-null    bool
dtypes: bool(13), boolean(2), float64(5), int64(2)
memory usage: 65.7 KB

None

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,heart_disease_present,sex_Male,...,dataset_VA Long Beach,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,True,150.0,False,2.3,0.0,0,True,...,False,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3.0,1,True,...,False,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,False,129.0,True,2.6,2.0,1,True,...,False,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,False,187.0,False,3.5,0.0,0,True,...,False,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,False,172.0,False,1.4,0.0,0,False,...,False,True,False,False,False,False,False,True,True,False

In [26]:
# Convert 'trestbps' and 'chol' to numeric, coercing errors to NaN
df['trestbps'] = pd.to_numeric(df['trestbps'], errors='coerce')
df['chol'] = pd.to_numeric(df['chol'], errors='coerce')

# Convert 'fbs' and 'exang' to boolean type
df['fbs'] = df['fbs'].astype('boolean')
df['exang'] = df['exang'].astype('boolean')

# Display updated info to verify data type changes
display(df.info())

# Display the first few rows to see the effect of type conversion
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       920 non-null    int64
 1   trestbps                  860 non-null    float64
 2   chol                      718 non-null    float64
 3   fbs                       830 non-null    boolean
 4   thalch                    865 non-null    float64
 5   exang                     865 non-null    boolean
 6   oldpeak                   858 non-null    float64
 7   ca                        309 non-null    float64
 8   heart_disease_present     920 non-null    int64
 9   sex_Male                  920 non-null    bool
 10  dataset_Hungary           920 non-null    bool
 11  dataset_Switzerland       920 non-null    bool
 12  dataset_VA Long Beach     920 non-null    bool
 13  cp_atypical angina        920 non-null    bool
 14  cp_non-anginal            920 non-null    bool
 15  cp_typical angina         920 non-null    bool
 16  restecg_normal            920 non-null    bool
 17  restecg_st-t abnormality  920 non-null    bool
 18  slope_flat                920 non-null    bool
 19  slope_upsloping           920 non-null    bool
 20  thal_normal               920 non-null    bool
 21  thal_reversable defect    920 non-null    bool
dtypes: bool(13), boolean(2), float64(5), int64(2)
memory usage: 65.7 KB

None

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,heart_disease_present,sex_Male,...,dataset_VA Long Beach,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,True,150.0,False,2.3,0.0,0,True,...,False,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,False,108.0,True,1.5,3.0,1,True,...,False,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,False,129.0,True,2.6,2.0,1,True,...,False,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,False,187.0,False,3.5,0.0,0,True,...,False,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,False,172.0,False,1.4,0.0,0,False,...,False,True,False,False,False,False,False,True,True,False